// Generated by https://quicktype.io

import { Areas } from "./areas.model";
import { Municipios } from "./municipios.model";
import { Personas } from "./personas.model";

export interface ActivosFijos {
  id:               number;
  nombre:           string;
  descripcion:      string;
  tipo:             string;
  serial:           null;
  numeroInventario: string;
  peso:             number;
  alto:             number;
  ancho:            number;
  largo:            number;
  valorCompra:      number;
  fechaCompra:      string;
  fechaBaja:        null;
  estado:           string;
  color:            string;
  area:             Areas;
  persona:          Personas;
  municipio:        Municipios;
}

