// Generated by https://quicktype.io

import { Municipios } from "./municipios.model";

export interface Areas {
  id:        number;
  nombre:    string;
  municipio: Municipios;
}

export interface AreasResponse{
  data: Areas[];
}




